#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your
# load-balancer IP (lb-01). Let’s also add other subdomains to make our life easier
# later (example: lb-01, web-01, web-02).

display() {
    local subdomain=$1
    local record_type=$2
    local destination=$3
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

subdomains=("www" "lb-01" "web-01" "web-02")

if [ $# -eq 2 ]; then
    record_type=$(dig $subdomain.$domain | grep -A1 "ANSWER SECTION" | tail -1 | awk '{print $4}')
    destination=$(dig $subdomain.$domain | grep -A1 "ANSWER SECTION" | tail -1 | awk '{print $5}')
    display $subdomain $record_type $destination
else
    for subdomain in "${subdomains[@]}"; do
        record_type=$(dig $subdomain.$domain | grep -A1 "ANSWER SECTION" | tail -1 | awk '{print $4}')
        destination=$(dig $subdomain.$domain | grep -A1 "ANSWER SECTION" | tail -1 | awk '{print $5}')
        display $subdomain $record_type $destination
    done
fi
