#!/usr/bin/env bash
# Nginx server to have a custom 404 page that contains the string
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo sed -i '/^}$/i \\n\tlocation /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default
sudo sed -i '/^}$/i \\n\tlocation @404 { return 404 "Ceci n'\''est pas une page\\n"; }' /etc/nginx/sites-available/default
sudo sed -i 's/=404/@404/g' /etc/nginx/sites-available/default
sudo service nginx restart
