#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect above requirements
hostname=$(hostname)
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=3lFkDc6dFoY;
    }
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
        internal;
    }
    add_header X-Served-By $hostname;
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
