#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get install -y haproxy
sudo sh -c 'echo "
frontend front
    bind *:80
    default_backend back

backend back
    balance roundrobin
    server web1 52.91.126.74:80 check
    server web2 34.224.15.231:80 check
    " >> /etc/haproxy/haproxy.cfg'

sudo service haproxy restart