#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
nginx="
server {
       listen 80 default_server;
       listen [::]:80 default_server;

       server_name localhost;

       root /var/www/html;
       index index.html index.nginx-debian.html;

       location / {
               try_files \$uri \$uri/ @404;
       }
}"
echo "$nginx" > /etc/nginx/sites-available/default
service nginx restart
