#!/usr/bin/env bash
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

clean()
{
    rm -rf /var/run/myscript.pid
    exit
}

handler()
{
    echo "I hate the kill command"
    clean
}

sigInt()
{
    echo "Y U no love me?!"
}

trap 'handler' SIGTERM
trap 'sigInt' SIGINT
trap 'clean' SIGQUIT

echo $$ > /var/run/myscript.pid

while true;
do
    echo "To infinity and beyond"
    sleep 2
done