#!/usr/bin/env bash
# script that installs ufw and sets up firewall

sudo apt-get update
sudo apt-get install ufw

sudo ufw default deny incoming

sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable

sudo ufw status
